### ISSUE TITLE
Missing password for Suso operation

### ISSUE THREAD

**Issue by PietKnot** [wellenvogel/avnav-update-plugin#6]
Running on Linux-laptop the operation of the update plugin generates sudo commands which require a password e.g. 
"sudo -n apt-get install -y avnav-history-plugin"
gives a reply 
"sudo: a password is required"
"command finished with return code 1"

where to enter this password or how to?
Using the Synaptic package manager all works fine after entering a password, thus no real problem.

**Comment by wellenvogel** [comment]
It requires a sudoers set up.
The plugin creates /etc/sudoers.d/avnavupdate - that has all the set ups for the user pi (the one avnav update is running).
This requires that the directory is included (see in /etc/sudoers).
And the updater process should run as user pi (if you did not change this). Otherwise you would need to adapt the sudoers config.
Hmm - but maybe the config does not really fit.
You could try to add an additional line:
pi ALL=(root)NOPASSWD:/usr/bin/apt-get install -y avnav*
Hard to check on a pi as there is a sudoers config for pi anyway ;-).

**Comment by PietKnot** [comment]
first of all maybe a missunderstanding: my laptop has a standard Linux installation without user PI  but instead using my own credentials created at moment of Linux installation..

As a Linux starter, i could not save the edited config-file: permission denied. No problem to handle this on windows, thus stupid question: how to get the permission to do so? Some sudo command?

**Comment by wellenvogel** [comment]
Hmm - so it would be helpful to know how you installed.
out of the box the updater plugin will only run with the user pi...
Not sure if you changed the override.conf.
I guess I need to add something to the doc.
If you run AvNav under the avnav user it potentially will make sense to also run the update plugin with the avnav user.
This will require a sudoers conf for AvNav.
So I guess there are 2 issues:
(1) find out on which user the updater is running on your system
(2)potentially adapt the config
To change files that belong to root you either need to become root on your system - or have sudo being available.
Typical installations provide a sudo for your main user.
Hint:
before changing the sudoers config just open a (second) terminal window and become root inside:
`sudo -i`
check this with
`id`
Leave this window open!
This will give you a "rescue" terminal window - if you make some error in the sudoers config a sudo command will not work afterwards - and you would have no chance to correct this as you cannot become root any more.
After making changes of the sudoers you can always test this by executing some command with sudo.

**Comment by PietKnot** [comment]
first answers to your questions:
1. when starting Linux32 from BunsenLabs and logging in, only Myself and AvNav are present, via "other" i tried Root but no tried password does match.
2. installed in the past AvNav manually using Synaptic and deinstalled again. After that, used the Paket Installation from www.free-x.de and with plugins (mapproxy fine)
3. did not change any "config file" e.g. override.conf.
4. to identify user to run update i started task-manager; the following users were present while the plugin-updater windows was visible (no-active task for updater):
users: avahi, avnav, daemon,lp, ntp, messagebu, myself, root. Nothing like "Pi" as user.
5. the "sudo -i" and id proves i can become root in terminal windows.
6. added the line as root which worked without problems

Now restarted the webbrowser session and AvNav-updater: still same problem as reported "password required"

Now restarted laptop and avnav: still problem: e.g. with refresh package info. thus adding the line does not resolve the problem.

Note: i can perfectly live with updater not working and do it manually.

**Comment by wellenvogel** [comment]
Ok, cross-checked again.
The updater plugin is intelligent enough ;-) to run as avnav if pi is not available.
And it should have set up the /etc/sudoers.d/avnavupdate correctly to contain lines for avnav instead of pi.
So I was not completely correct - the line must be:
avnav ALL=(root)NOPASSWD:/usr/bin/apt-get install -y avnav*

OK - just made some correction in the sudoers file - package is just building.
So you can just update the plugin.
Best would be to reboot afterwards to make the changes effective.

**Comment by PietKnot** [comment]
Thnx; looks like all is working now with version 20220402. Installed the history-plugin using the update-plugin.

leaving the error (most probably normal) with "Refresh package info" command
"starting usdo -n ntp-date pool.ntp.org"
gives error with return code 1 "the NTP socket is in use"

**Comment by wellenvogel** [comment]
The remaining error most probably is caused by your system already having an NTP service running. We avoid this on our images as it can easily interfere with the attempt of avnav to set the system time (but setting the system time is only enabled if you installed avnav-raspi).
So I guess for now we can safely ignore this error.
If you would like to utilize your laptop on board you may want to think about the way time synchronization should work if it is not connected to the internet.
